### ISSUE TITLE
File input request

### ISSUE THREAD

**Issue by lzomedia** [TiDJ/laravel-custom-html#5]
It would be great to have

**Comment by TiDJ** [comment]
Hi @lzomedia , you can do it both of these ways

With the control call, generating for you a label and parent block

```php
{!! Form::control('file', 'thumbnail', $errors, [
    'label' => 'Your thumbnail',
]) !!}
```

Or just the input

```php
{!! Form::input('file', 'thumbnail', $errors)  !!}
```

And don't forget the ```'files' => true``` in the ```Form::model() or Form::open() ```

You can use every call of the default LaravelCollective Html&Form package, doc available here : https://laravelcollective.com/docs/master/html#file-input

**Comment by JGamboa** [comment]
@TiDJ i made a pull request
